"""
amounts.py — Convert integer cent amounts to check display strings.

Two outputs are required by buildspec.md §6:

  1. Courtesy amount  — the numeric figure in the boxed field, e.g. "**1,250.00"
                        with leading fill characters to prevent digit prepending.

  2. Legal amount     — the written-out text on the legal amount line, e.g.
                        "One Thousand Two Hundred Fifty and 00/100"
                        followed by a fill rule ("***...***") to the line end.

Rule (UCC §3-114, buildspec.md §6): if the two amounts disagree, the legal
(written) amount controls. Both amounts are derived from the *same*
amount_cents integer — they can never disagree when generated by this code.

No floats anywhere in this module. All arithmetic is in integer cents.
"""


# ---------------------------------------------------------------------------
# Ones, tens, teens lookup tables
# ---------------------------------------------------------------------------

_ONES = [
    "", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
    "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen",
    "Sixteen", "Seventeen", "Eighteen", "Nineteen",
]

_TENS = [
    "", "", "Twenty", "Thirty", "Forty", "Fifty",
    "Sixty", "Seventy", "Eighty", "Ninety",
]

_SCALES = [
    (1_000_000, "Million"),
    (1_000,     "Thousand"),
    (100,       "Hundred"),
]


def _three_digit_words(n: int) -> str:
    """Convert an integer 1–999 to English words."""
    if n <= 0 or n >= 1000:
        raise ValueError(f"_three_digit_words expects 1–999, got {n}")

    parts = []
    hundreds = n // 100
    remainder = n % 100

    if hundreds:
        parts.append(f"{_ONES[hundreds]} Hundred")

    if remainder < 20:
        if remainder:
            parts.append(_ONES[remainder])
    else:
        tens_word = _TENS[remainder // 10]
        ones_word = _ONES[remainder % 10]
        parts.append(f"{tens_word}{'-' + ones_word if ones_word else ''}")

    return " ".join(parts)


def _dollars_to_words(dollars: int) -> str:
    """Convert a non-negative integer number of dollars to English words."""
    if dollars == 0:
        return "Zero"

    parts = []
    for threshold, name in [(1_000_000, "Million"), (1_000, "Thousand")]:
        chunk = dollars // threshold
        if chunk:
            parts.append(f"{_three_digit_words(chunk)} {name}")
            dollars %= threshold

    if dollars:
        parts.append(_three_digit_words(dollars))

    return " ".join(parts)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def cents_to_courtesy(amount_cents: int, fill_char: str = "*") -> str:
    """
    Format an integer cent amount as the courtesy-amount box string.

    Format: fill_char * (width - len(numeric)) + numeric
    where numeric = "$1,250.00" and the total width is 10 characters
    (leaving 2 fill chars minimum as a prepend guard).

    Examples:
        125         → "****$1.25"
        125000      → "**$1,250.00"
        999999999   → "$9,999,999.99"   (no fill — number fills the box)

    Raises ValueError if amount_cents ≤ 0.
    """
    if amount_cents <= 0:
        raise ValueError(f"amount_cents must be positive, got {amount_cents}")

    dollars = amount_cents // 100
    cents = amount_cents % 100

    numeric = f"${dollars:,}.{cents:02d}"

    # Minimum total width = max(len(numeric)+2, 10)
    total_width = max(len(numeric) + 2, 10)
    padding = fill_char * (total_width - len(numeric))
    return padding + numeric


def cents_to_legal(amount_cents: int, line_width: int = 60) -> str:
    """
    Format an integer cent amount as the legal (written) amount string,
    padded with trailing asterisks to ``line_width`` characters.

    Example output (line_width=60):
        "One Thousand Two Hundred Fifty and 00/100***...**"

    Per UCC §3-114: the legal amount controls over the courtesy amount.
    Both are derived from the same source to prevent any mismatch.

    Raises ValueError if amount_cents ≤ 0.
    """
    if amount_cents <= 0:
        raise ValueError(f"amount_cents must be positive, got {amount_cents}")

    dollars = amount_cents // 100
    cents = amount_cents % 100

    word_dollars = _dollars_to_words(dollars)
    legal_text = f"{word_dollars} and {cents:02d}/100"

    # Fill the rest of the line with asterisks (prepend-guard for alterations).
    if len(legal_text) < line_width:
        fill = "*" * (line_width - len(legal_text))
        return legal_text + fill
    else:
        # Amount text is longer than the line — truncation would be dangerous,
        # so return as-is and let the renderer wrap/adjust.
        return legal_text


def cents_to_display(amount_cents: int) -> tuple[str, str]:
    """
    Convenience wrapper: returns (courtesy_str, legal_str) together.

    Both are derived from the same amount_cents so they always agree
    (satisfying UCC §3-114 by construction).
    """
    return cents_to_courtesy(amount_cents), cents_to_legal(amount_cents)


def parse_amount_string(amount_str: str) -> int:
    """
    Parse a dollar amount string (e.g. "1,250.00" or "$1,250.00") into cents.

    Useful when ingesting amounts from CSV reconciliation files.
    Raises ValueError on malformed input.
    """
    s = amount_str.strip().lstrip("$").replace(",", "")
    try:
        value = float(s)
    except ValueError:
        raise ValueError(f"Cannot parse amount string: {amount_str!r}")

    # Round to cents and convert to int.
    return int(round(value * 100))


def cents_to_remittance_courtesy(amount_cents: int) -> str:
    """
    Format courtesy amount in remittance check style, e.g. "$**5,000.00".
    Leading dollar sign, followed by guard asterisks and formatted dollar figure.
    """
    if amount_cents <= 0:
        raise ValueError(f"amount_cents must be positive, got {amount_cents}")
    dollars = amount_cents // 100
    cents = amount_cents % 100
    return f"$**{dollars:,}.{cents:02d}"


def cents_to_remittance_legal(amount_cents: int, use_xx_for_zero_cents: bool = True) -> str:
    """
    Format legal amount in remittance check style, e.g.
    "**FIVE THOUSAND AND XX/100 DOLLAR**".
    """
    if amount_cents <= 0:
        raise ValueError(f"amount_cents must be positive, got {amount_cents}")
    dollars = amount_cents // 100
    cents = amount_cents % 100

    word_dollars = _dollars_to_words(dollars).upper()
    if cents == 0 and use_xx_for_zero_cents:
        cents_part = "XX/100"
    else:
        cents_part = f"{cents:02d}/100"

    return f"**{word_dollars} AND {cents_part} DOLLAR**"

